REM https://cmake.org/pipermail/cmake/2007-December/018548.html booleanos de cmake
REM https://cmake.org/cmake/help/latest/command/if.html booleanos en cmake txt
set CMAKE= ..\..\Dependencies\CMake\bin\cmake.exe
set SOURCE= ..\..\Dependencies\Ogre\src
set BUILD = .\build
mkdir build
cd build

%CMAKE% -DOGRE_BUILD_COMPONENT_BULLET:BOOL=NO -DOGRE_BUILD_COMPONENT_BITES:BOOL=NO ^
-DOGRE_BUILD_COMPONENT_TERRAIN:BOOL=NO -DOGRE_BUILD_COMPONENT_VOLUME:BOOL=NO ^
-DOGRE_BUILD_PLUGIN_ASSIMP:BOOL=NO -DOGRE_BUILD_PLUGIN_BSP:BOOL=NO -DOGRE_BUILD_PLUGIN_DOT_SCENE:BOOL=NO ^
-DOGRE_BUILD_PLUGIN_DOT_SCENE:BOOL=NO -DOGRE_BUILD_PLUGIN_OCTREE:BOOL=NO ^
-DOGRE_BUILD_PLUGIN_PCZ:BOOL=NO -DOGRE_BUILD_PLUGIN_STBI:BOOL=NO -DOGRE_BUILD_RENDERSYSTEM_D3D11:BOOL=NO ^
-DOGRE_BUILD_RENDERSYSTEM_GL:BOOL=NO -DOGRE_BUILD_RENDERSYSTEM_GLES2:BOOL=NO -DOGRE_BUILD_SAMPLES:BOOL=NO ^
-DOGRE_BUILD_TOOLS:BOOL=NO -DOGRE_INSTALL_DEPENDENCIES:BOOL=ON -DOGRE_INSTALL_DOCS:BOOL=NO -DOGRE_INSTALL_SAMPLES:BOOL=NO ^
-DOGRE_INSTALL_TOOLS:BOOL=NO -DOGRE_INSTALL_VSPROPS:BOOL=ON %SOURCE%



ECHO %CMAKE%
set /p asd="Hit enter to continue"